### ISSUE TITLE
 PGP signature

### ISSUE THREAD

**Issue by genestealer** [Fohdeesha/idrac-7-8-reverse-engineering#2]
Please, please, please can you provide the instructions on bypassing Dell's PGP signature checks to load and run the modified firmware onto the controller?

**Comment by BrandonLeeDotDev** [comment]
Bump

**Comment by Fohdeesha** [comment]
Hi, it involved creating your own squashfs firmware package, breaking into the bootloader with physical UART access, and flashing it to flash, replacing the stock dell firmware package
